src/models/user.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from src.extensions import db
from src.models.base import BaseModel


class User(BaseModel, UserMixin):

    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String)
    name = db.Column(db.String)
    surname = db.Column(db.String)
    email = db.Column(db.String)
    sex = db.Column(db.String)
    _password = db.Column(db.String)
    role_id = db.Column(db.Integer, db.ForeignKey("roles.id"))

    role = db.relationship("Role", uselist = False)
    petitions = db.relationship("Petition", back_populates="user")


    @property
    def password(self):
        return self._password
    

    @password.setter
    def password(self, value):
        self._password = generate_password_hash(value)


    def check_password_hash(self, password):
        return check_password_hash(self._password, password)
    

    def is_admin(self):
        return self.role_id == 1


    def __repr__(self) -> str:
        return self.username


class Role(BaseModel):

    __tablename__ = "roles"

    id = db.Column(db.Integer, primary_key=True)
    user_role = db.Column(db.String)

    
    def __repr__(self) -> str:
        return self.user_role

src/views/user/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import StringField, SubmitField, PasswordField, TextAreaField, IntegerField
from wtforms.validators import DataRequired, equal_to, length


class EditUser(FlaskForm):
    name = StringField("name", validators=[DataRequired()], render_kw={"class": "form-control", 
                                                                       "placeholder": "Name",
                                                                        "style": "background-color:#ce5a67; border: 0px;"})
    surname = StringField("surname", validators=[DataRequired()], render_kw={"class": "form-control", 
                                                                       "placeholder": "Last Name",
                                                                        "style": "background-color:#ce5a67; border: 0px;"})
    password = PasswordField("password", render_kw={"class": "form-control",
                                                                       "placeholder": "Password",
                                                                        "style": "background-color:#ce5a67; border: 0px;"})
    
    repeat_password = PasswordField("repeat_password", validators=[equal_to("password", message="პაროლები არ ემთხვევა")] ,
                                                                    render_kw={"class": "form-control",
                                                                       "placeholder": "Repeat Password",
                                                                        "style": "background-color:#ce5a67; border: 0px;"})  

    submit = SubmitField("დადასტურება", render_kw={
        "class": "btn",
        "style": "background-color: #ce5a67; margin: 20px; padding: 15px; margin-bottom: 40px;"
    })


class EditPetition(FlaskForm):
    name = StringField("Name", validators=[DataRequired()], render_kw={"type": "text", 
                                                                       "class": "form-control", 
                                                                       "placeholder": "Name",
                                                                        "style": "background-color:#ce5a67; border: 0px;"})
    title = StringField("Title", validators=[DataRequired()], render_kw={"type": "text", 
                                                                       "class": "form-control", 
                                                                       "placeholder": "Title",
                                                                        "style": "background-color:#ce5a67; border: 0px;"})
    address = StringField("Address", validators=[DataRequired()], render_kw={"type": "text", 
                                                                       "class": "form-control", 
                                                                       "placeholder": "Address",
                                                                        "style": "background-color:#ce5a67; border: 0px;"})
    description = TextAreaField("Description", validators=[DataRequired(), length(min=50)], render_kw={"type": "text", 
                                                                       "class": "form-control", 
                                                                       "placeholder": "Description",
                                                                        "style": "background-color:#ce5a67; border: 0px;",
                                                                        "rows": "10", "cols": "45"})
    short_description = StringField("Short Description", validators=[DataRequired(), length(max=200)], render_kw={"type": "text", 
                                                                       "class": "form-control", 
                                                                       "placeholder": "Short Description",
                                                                        "style": "background-color:#ce5a67; border: 0px;",
                                                                        "rows": "5", "cols": "45"})

    submit = SubmitField("პეტიციის რედაქტირება", render_kw={
        "class":"btn", 
        "type":"submit", 
        "style": "background-color: #ce5a67; margin: 20px; padding: 20px; margin-bottom: 40px;"
    })

src/views/petitions/routes.py
from flask import render_template, redirect, url_for, request, Blueprint, flash
from flask_login import current_user, login_required

from uuid import uuid4
from datetime import datetime
import os

from src.models import Petition, Signer, PetitionSigner, User
from src.config import Config, to_english
from src.views.petitions.forms import AddPetition, SignPetition

TEMPLATES_FOLDER = os.path.join(Config.BASE_DIRECTORY, "templates", "petitions")
petitions = Blueprint("petitions", __name__, template_folder=TEMPLATES_FOLDER)


@petitions.route("/petition/<string:name>")
def petition(name):
    to_display = Petition.query.filter(Petition.url_name == name).scalar()

    return render_template("petition.html", petition=to_display)


@petitions.route("/sign_petition", methods=["GET", "POST"])
def sign_petition():
    form = SignPetition()

    if current_user.is_authenticated:
        form = SignPetition(
            obj=current_user
        )

    petition_id = request.args.get("petition_id")

    if form.validate_on_submit():

        exists = False

        to_sign = Petition.query.get(petition_id)

        for signer in to_sign.signers:
            if signer.personal_id == form.personal_id.data or signer.email == form.email.data:
                exists = True

        if not exists:
            new_signer = Signer(
                name=form.name.data,
                surname=form.surname.data,
                email=form.email.data,
                personal_id=form.personal_id.data,
                sex=form.sex.data,
                number=form.number.data,
                city=form.city.data,
                date=form.date.data
            )

            new_signer.create()

            petition_signer = PetitionSigner(petition_id=petition_id, signer_id=new_signer.id)
            petition_signer.create()

            to_sign.votes = len(to_sign.signers)
            to_sign.save()

            return redirect(url_for("main.home"))
        else:
            flash("You have already signed this petition!")

    return render_template("sign-form.html", form=form)


@petitions.route("/create_petition", methods=["GET", "POST"])
@login_required
def create_petition():
    form = AddPetition()
    method = request.args.get("img")

    if form.validate_on_submit():

        name = to_english(form.name.data)
        upload_time = str(datetime.now().time())
        img_path = f"{name}{upload_time}"

        new_petition = Petition(
            user_id=current_user.id,
            name=form.name.data,
            title=form.title.data,
            address=form.address.data,
            description=form.description.data,
            short_description=form.short_description.data,
            url_name=name,
            img1=form.main_img_l.data,
            img2=form.left_img2_l.data,
            img3=form.left_img1_l.data,
            img4=form.right_img1_l.data,
            img5=form.right_img2_l.data,
            method="link",
            goal=form.goal.data,
            votes=0
        )

        if method == "upload":
            new_petition.method = "upload"
            os.makedirs(os.path.join(Config.UPLOAD_PATH, img_path), exist_ok=True)

            counter = 1
            for key, value in form.data.items():
                if key in Config.UPLOADING_IMAGES:
                    file = value

                    filename, filetype = file.filename.split(".")
                    filename = str(uuid4())
                    fullname = f"{filename}.{filetype}"

                    upload_path = os.path.join(Config.UPLOAD_PATH, img_path, fullname)
                    file.save(upload_path)

                    setattr(new_petition, f"img{counter}", f"./static/assets/{img_path}/{fullname}")
                    counter += 1

        new_petition.create()

        return redirect(url_for("main.home"))

    return render_template("create-petition.html", form=form, img=method)

src/views/user/routes.py
from flask import render_template, redirect, url_for, request, Blueprint
from flask_login import current_user, login_required

import os

from src.models import Petition, User
from src.config import Config
from src.views.user.forms import EditPetition, EditUser

TEMPLATES_FOLDER = os.path.join(Config.BASE_DIRECTORY, "templates", "user")
user = Blueprint("user", __name__, template_folder=TEMPLATES_FOLDER)


@user.route("/user/<string:username>", methods=["GET", "POST"])
def user_profile(username):
    signed = []
    user_prof = User.query.filter(User.username == username).first()

    if user_prof is None:
        return redirect(url_for("main.error", code="404"))

    data = Petition.query.filter(Petition.user_id == user_prof.id).all()
    petitions = Petition.query.all()

    for petition in petitions:
        for each in petition.signers:
            if each.email == user_prof.email:
                signed.append(petition)

    if current_user.is_authenticated and current_user.id == user_prof.id:

        form = EditUser(
            name=user_prof.name,
            surname=user_prof.surname,
        )

        if form.validate_on_submit and request.method == "POST":
            user_prof.name = form.name.data
            user_prof.surname = form.surname.data
            user_prof.password = form.password.data

            user_prof.save()

        return render_template("user.html", user=user_prof, form=form, data=data, signed=signed,
                               count=[len(data), len(signed)])

    return render_template("guest_user.html", user=user_prof, data=data, signed=signed,
                           count=[len(data), len(signed)])


@user.route("/delete/<int:id>")
def delete(id):
    petition = Petition.query.get(id)

    petition.remove()

    return redirect(url_for("user.user_profile", username=current_user.username))


@user.route("/edit/<int:id>", methods=["GET", "POST"])
def edit(id):
    petition = Petition.query.get(id)
    form = EditPetition(
        name=petition.name,
        title=petition.title,
        address=petition.address,
        description=petition.description,
        short_description=petition.short_description,
    )

    petition.name = form.name.data
    petition.title = form.title.data
    petition.address = form.address.data
    petition.description = form.description.data
    petition.short_description = form.short_description.data

    return render_template("edit_petition.html", user=user, form=form)

src/templates/user/edit_petition.html
{% extends "layouts/base.html" %}

{% block content %}
<div class="container text-center text_div">
    <h2 style="margin:20px; text-align: center;">პეტიციის რედაქტირება</h2>
    <hr>
    <div class="d-flex justify-content-center">
        <form method="post" enctype="multipart/form-data">
            {{ form.hidden_tag() }}

            <br>
            <br>
            <h4 class="form-label w-100">შეიყვანეთ ინფორმაცია</h4>
            <hr>
            <br>

            <div class="mb-3">
                <label class="form-label">დასახელება</label>
                {{ form.name }}
            </div>

            <div class="mb-3">
                <label class="form-label">სათაური</label>
                {{ form.title }}
            </div>

            <div class="mb-3">
                <label class="form-label">ადრესატი</label>
                {{ form.address }}
            </div>

            <div class="mb-3">
                <label class="form-label">ტექსტი</label>
                {{ form.description }}
            </div>

            <div class="mb-3">
                <label class="form-label">მოკლე მიმოხილვა</label>
                {{ form.short_description }}
            </div>
            
            <br>
            {{ form.submit }}
        </form>
    </div>
</div>
{% endblock %}

src/templates/user/guest_user.html
{% extends "layouts/base.html" %}

{% block content %}
<div class="container">
    <div class="text-center">
        <p class="d-inline-flex gap-1">
            <button class="btn" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample"
                    aria-expanded="false" aria-controls="collapseExample"
                    style="background-color: #ce5a67; font-size:30px; margin: 20px; padding: 15px 50px">
                მომხმარებლის ინფორმაცია
            </button>
        </p>
    </div>
    <div class="container text-center text_div w-50">
        <div class="collapse" id="collapseExample">
            <div class="container text-center text_div">
                <h2 style="margin:20px; text-align: center;">{{ user.username }}</h2>
                <hr>
                <br>
                <div class="d-flex justify-content-center">
                    <div class="mb-3">
                        <div class=" image d-flex flex-column justify-content-center align-items-center">
                            {% if user.sex == "male" %}
                                <img src="{{ url_for('static', filename='assets/male.png') }}" height="100" width="100"/>
                            {% elif user.sex == "female" %}
                                <img src="{{ url_for('static', filename='assets/female.png') }}" height="100" width="100"/>
                            {% else %}
                                <img src="{{ url_for('static', filename='assets/other.png') }}" height="100" width="100"/>
                            {% endif %}
                            <span class="name mt-3">{{ user.name }} {{ user.surname }}</span>
                            <span class="idd mt-2" style="color: #ce5a67">{{user.role.user_role}}</span>
                            <span class="idd mt-2">{{user.email}}</span>
                            <span class="idd mt-2">შექმნილი პეტიციები: {{ count[0] }}</span>
                            <span class="idd">ხელმოწერილი პეტიციები: {{ count[1] }}</span>
                        </div>
                        <br>
                    </div>
                </div>
            </div>
        </div>

    </div>

</div>
<br>
<br>
<h2 style="text-align: center;">{{ user.username }}-ის პეტიციები</h2>
<hr>
<br>
<div class="container-fluid">
    <div class="row gy-4 text-center">
        {% if data == [] %}
        <h3 style="padding:20px 0px 40px 0px;">მომხმარებელს ჯერ არ აქვს პეტიცია შექმნილი</h3>
        {% endif %}
        {% for each_post in data %}
        <div class="col-xxl-2 col-xl-3 col-lg-4 col-md-5 col-sm-6">
            <div class="card" style="width: 16rem; background-color: #f4bf96">
                <img src="{% if each_post.method == 'upload' %}.{% endif%}{{ each_post.img1 }}" class=" card-img-top"
                     alt="..." width="200px" height="240px">
                <div class="card-body">
                    <h5 class="card-title" style="height:100px;"> {{ each_post.title }}</h5>
                    <hr>
                    <p class="card-text" style="height: 200px; width:227px; overflow:scroll">{{
                        each_post.short_description }}</p>
                    <a href="{{ url_for('petitions.petition', name=each_post.url_name) }}" class="btn"
                       style="background-color: #ce5a67">სრულად</a>
                    <br>
                </div>
            </div>
            <br>
            <br>
        </div>
        {% endfor %}
    </div>
</div>


<br>
<br>

{% if data == [] and signed == [] %}
<br>
<br>
<br>
<br>
<br>
<br>
{% endif %}

<h2 style="text-align: center;">{{ user.username }}-ის ხელმოწერები</h2>
<hr>
<br>
<div class="container-fluid">
    <div class="row gy-4 text-center">
        {% if signed == [] %}

        <h3 style="padding:20px 0px 40px 0px;">მომხმარებელს ჯერ არ აქვს პეტიცია ხელმოწერილი</h3>

        {% endif %}
        {% for each_post in signed %}
        <div class="col-xxl-2 col-xl-3 col-lg-4 col-md-5 col-sm-6">
            <div class="card" style="width: 16rem; background-color: #f4bf96">
                <img src="{% if each_post.method == 'upload' %}.{% endif%}{{ each_post.img1 }}" class=" card-img-top"
                     alt="..." width="200px" height="240px">
                <div class="card-body">
                    <h5 class="card-title" style="height:100px;"> {{ each_post.title }}</h5>
                    <hr>
                    <p class="card-text" style="height: 200px; width:227px; overflow:scroll">{{
                        each_post.short_description }}</p>
                    <a href="{{ url_for('petitions.petition', name=each_post.url_name) }}" class="btn"
                       style="background-color: #ce5a67">სრულად</a>
                    <br>
                    <br>
                    <p style="font-size: small;">ავტორი --> <a
                            style="color: #ce5a67; text-decoration: none; font-size: medium;"
                            href="{{ url_for('user.user_profile', username=each_post.user.username) }}">{{each_post.user.username}}</a>
                    </p>
                </div>
            </div>
            <br>
            <br>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

src/templates/user/user.html
{% extends "layouts/base.html" %}

{% block content %}
<div class="container w-75">
    <h1 style="margin:20px; text-align: center;">{{ user.username }}</h1>
    <hr>

    <div class="text-center">
        <p class="d-inline-flex gap-1">
            <button class="btn" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample"
                    aria-expanded="false" aria-controls="collapseExample"
                    style="background-color: #ce5a67; font-size:30px; margin: 20px; padding: 15px 50px">
                პროფილის რედაქტირება
            </button>
        </p>
    </div>
    <div class="container text-center text_div w-50">
        <div class="collapse" id="collapseExample">
            <div class="container text-center text_div">
                <div class="mb-3">
                    <div class="image d-flex flex-column justify-content-center align-items-center">
                        {% if user.sex == "male" %}
                        <img src="{{ url_for('static', filename='assets/male.png') }}" height="100" width="100" style="margin-top: 30px;"/>
                        {% elif user.sex == "female" %}
                        <img src="{{ url_for('static', filename='assets/female.png') }}" height="100" width="100" style="margin-top: 30px;"/>
                        {% else %}
                        <img src="{{ url_for('static', filename='assets/other.png') }}" height="100" width="100" style="margin-top: 30px;"/>
                        {% endif %}
                        <span class="name mt-3">{{ user.name }} {{ user.surname }}</span>
                        <span class="idd mt-2" style="color: #ce5a67">{{user.role.user_role}}</span>
                        <span class="idd mt-2">{{user.email}}</span>
                        <span class="idd mt-2">შექმნილი პეტიციები: {{ count[0] }}</span>
                        <span class="idd">ხელმოწერილი პეტიციები: {{ count[1] }}</span>
                    </div>
                    <br>
                </div>
                <h2 style="margin:20px; text-align: center;">პროფილის რედაქტირება</h2>
                <hr>
                <div class="d-flex justify-content-center">
                    <form method="post">

                        <br>

                        {% if form.errors %}
                        {% for field, errors in form.errors.items() %}
                        {% for error in errors %}
                        <div class="alert alert-danger" role="alert">
                            * {{ error }}
                        </div>
                        {% endfor %}
                        {% endfor %}
                        <br>
                        {% endif%}

                        {% with messages = get_flashed_messages() %}
                        {% if messages %}
                        {% for message in messages %}
                        <div class="alert alert-danger d-flex align-items-center" role="alert">
                            {{ message }}
                        </div>
                        {% endfor %}
                        {% endif %}
                        {% endwith %}

                        {{ form.hidden_tag() }}

                        <div class="mb-3">
                            <label class="form-label">სახელი</label>
                            {{ form.name }}
                        </div>

                        <div class="mb-3">
                            <label class="form-label">გვარი</label>
                            {{ form.surname }}
                        </div>

                        <div class="mb-3">
                            <label class="form-label">პაროლი</label>
                            {{ form.password }}
                        </div>

                        <div class="mb-3">
                            <label class="form-label">გაიმეორე პაროლი</label>
                            {{ form.repeat_password }}
                        </div>
                        <br>
                        {{ form.submit }}
                    </form>
                </div>
            </div>
        </div>

    </div>

</div>
<br>
<br>
<h2 style="text-align: center;">ჩემი პეტიციები</h2>
<hr>
<br>
<div class="container-fluid">
    <div class="row gy-4 text-center">
        {% if data == [] %}
        <h3 style="padding:20px 0px 40px 0px;">შენ ჯერ არ გაქვს პეტიცია შექმნილი. <a class="btn"
                                                                                     href="{{url_for('petitions.create_petition', img='upload')}}"
                                                                                     style="color: #ce5a67;"><h3>შექმენი
            ახლავე</h3></a></h3>
        {% endif %}
        {% for each_post in data %}
        <div class="col-xxl-2 col-xl-3 col-lg-4 col-md-5 col-sm-6">
            <div class="card" style="width: 16rem; background-color: #f4bf96">
                <img src="{% if each_post.method == 'upload' %}.{% endif %}{{ each_post.img1 }}" class=" card-img-top"
                     alt="..." width="200px" height="240px">
                <div class="card-body">
                    <h5 class="card-title" style="height:100px;"> {{ each_post.title }}</h5>
                    <hr>
                    <p class="card-text" style="height: 200px; width:227px; overflow:scroll">{{
                        each_post.short_description }}</p>
                    <a href="{{ url_for('user.delete', id=each_post.id) }}" class="btn"
                       style="background-color: #ce5a67">წაშლა</a>

                    <a href="{{ url_for('user.edit', id=each_post.id) }}" class="btn"
                       style="background-color: #ce5a67">რედაქტირება</a>

                    <br>
                </div>
            </div>
            <br>
            <br>
        </div>
        {% endfor %}
    </div>
</div>


<br>
<br>
<br>
{% if data == [] and signed == [] %}
<br>
<br>
<br>
<br>
<br>
<br>
{% endif %}

<h2 style="text-align: center;">ჩემი ხელმოწერები</h2>
<hr>
<br>
<div class="container-fluid">
    <div class="row gy-4 text-center">
        {% if signed == [] %}
        <h3 style="padding:20px 0px 40px 0px;">შენ ჯერ არ გაქვს პეტიცია ხელმოწერილი</h3>
        {% endif %}
        {% for each_post in signed %}
        <div class="col-xxl-2 col-xl-3 col-lg-4 col-md-5 col-sm-6">
            <div class="card" style="width: 16rem; background-color: #f4bf96">
                <img src="{% if each_post.method == 'upload' %}.{% endif%}{{ each_post.img1 }}" class=" card-img-top"
                     alt="..." width="200px" height="240px">
                <div class="card-body">
                    <h5 class="card-title" style="height:100px;"> {{ each_post.title }}</h5>
                    <hr>
                    <p class="card-text" style="height: 200px; width:227px; overflow:scroll">{{
                        each_post.short_description }}</p>
                    <a href="{{ url_for('petitions.petition', name=each_post.url_name) }}" class="btn"
                       style="background-color: #ce5a67">სრულად</a>
                    <br>
                    <br>
                    <p style="font-size: small;">ავტორი --> <a
                            style="color: #ce5a67; text-decoration: none; font-size: medium;"
                            href="{{ url_for('user.user_profile', username=each_post.user.username) }}">{{each_post.user.username}}</a>
                    </p>
                </div>
            </div>
            <br>
            <br>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}