src/models/base.py
from src.extensions import db


class BaseModel(db.Model):

    __abstract__ = True

    def create(self, commit=True):
        db.session.add(self)

        if commit:
            self.save()
        else:
            db.session.flush()
            

    def save(self):
        db.session.commit()


    def remove(self):
        db.session.delete(self)
        db.session.commit()
        

src/views/main/routes.py
from flask import render_template, request, Blueprint, redirect, url_for
from flask_login import current_user

from src.models import Petition, User
from src.config import Config
from src.views.petitions.forms import AddPetition

import os

TEMPLATES_FOLDER = os.path.join(Config.BASE_DIRECTORY, "templates", "main")
main = Blueprint("main", __name__, template_folder=TEMPLATES_FOLDER)


@main.route("/", methods=["GET", "POST"])
def home():
    name = request.form.get("search")
    data = Petition.query.all()

    if name:
        data = Petition.query.filter(Petition.title.ilike(f"%{name}%")).all()
        return render_template("index.html", data=data)

    return render_template("index.html", data=data)


@main.route("/contact")
def contact():
    return render_template("errors/working.html")


@main.route("/error", methods=["GET", "POST"])
def error():
    error_code = request.args.get("code")
    if error_code is None:
        error_code = "404"
    return render_template(f"errors/{error_code}.html")

src/templates/layouts/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    {% block title %}
        <title>პეტიციების პორტალი</title>
    {% endblock %}
    <link rel="icon" href="{{ url_for('static', filename='assets/icon.svg') }}" type="image/x-icon" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/custom.css') }}" type="text/css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Roboto:400,700" />
    <style>
        .progress-bar {
                background-color: #fcf5ed;
            }
        .progress {
                background-color: #fcf5ed;
            }
    </style>
</head>

<body class="bg-custom">
    {% include "layouts/navlink.html"%}
      

    {% block content %}
    {% endblock %}
 
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>

</html>

src/templates/layouts/navlink.html
{% from "macros.html" import create_navlink %}

<nav class="bg-custom navbar navbar-expand-lg">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('main.home') }}" style="color: #ce5a67"><b>მთავარი</b></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav" >
                {{ create_navlink("petitions.create_petition", "პეტიციის შექმნა") }}
                {{ create_navlink("main.contact", "კონტაქტი") }}

                {% if current_user.is_authenticated %}

                    {% if current_user.is_admin() %}
                            <a class="nav-link" href="{{url_for('admin.index')}}">Admin Panel</a>
                    {% endif %}
          
                    {{ create_navlink("user.user_profile", current_user.username) }}
                    {{ create_navlink("auth.logout", "გასვლა") }}
                {% else %}
                    {{ create_navlink("auth.login", "შესვლა") }}
                    {{ create_navlink("auth.register", "რეგისტრაცია") }}
                {% endif %}

            </div>

        </div>

        <form class="d-flex" role="search" method="post" action="{{url_for('main.home')}}">
            <input class="form-control me-2" type="search" placeholder="მოძებნე პეტიცია" aria-label="Search" name="search">
            <button class="btn" style="background-color: #ce5a67;color: #1f1717;" type="submit">ძებნა</button>
        </form>
    </div>
</nav>
<hr style="margin-bottom: 40px;">