src/models/petitions.py
from src.extensions import db
from src.models.base import BaseModel

class Petition(BaseModel):

    __tablename__ = "petitions"

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))

    name = db.Column(db.String)
    title = db.Column(db.String)
    address = db.Column(db.String)
    description = db.Column(db.String)
    short_description = db.Column(db.String)
    url_name = db.Column(db.String)
    img1 = db.Column(db.String)
    img2 = db.Column(db.String)
    img3 = db.Column(db.String)
    img4 = db.Column(db.String)
    img5 = db.Column(db.String)
    method = db.Column(db.String)
    goal = db.Column(db.Integer)
    votes = db.Column(db.Integer)

    signers = db.relationship("Signer", back_populates="petitions", secondary="petition_signer")
    user = db.relationship("User", back_populates="petitions")


    def __repr__(self) -> str:
        return self.url_name
    

class PetitionSigner(BaseModel):

    __tablename__  = "petition_signer"

    id = db.Column(db.Integer, primary_key=True)
    petition_id = db.Column(db.Integer, db.ForeignKey("petitions.id"))
    signer_id = db.Column(db.Integer, db.ForeignKey("signers.id"))


class Signer(BaseModel):

    __tablename__ = "signers"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)
    surname = db.Column(db.String)
    email = db.Column(db.String)
    personal_id = db.Column(db.Integer)
    sex = db.Column(db.String)
    number = db.Column(db.Integer)
    city = db.Column(db.String)
    date = db.Column(db.String)

    petitions = db.relationship("Petition", back_populates="signers", secondary="petition_signer")


    def __repr__(self) -> str:
        return str(self.personal_id)
    

src/views/petitions/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import StringField, SubmitField, TextAreaField, IntegerField, EmailField, SelectField, DateField
from wtforms.validators import DataRequired, length, Email
from flask_wtf.file import FileField
import email_validator


class AddPetition(FlaskForm):
    name = StringField("Name", validators=[DataRequired()], render_kw={"type": "text",
                                                                       "class": "form-control",
                                                                       "placeholder": "Name",
                                                                       "style": "background-color:#ce5a67; border: 0px;"})
    title = StringField("Title", validators=[DataRequired()], render_kw={"type": "text",
                                                                         "class": "form-control",
                                                                         "placeholder": "Title",
                                                                         "style": "background-color:#ce5a67; border: 0px;"})
    address = StringField("Address", validators=[DataRequired()], render_kw={"type": "text",
                                                                             "class": "form-control",
                                                                             "placeholder": "Address",
                                                                             "style": "background-color:#ce5a67; border: 0px;"})
    description = TextAreaField("Description", validators=[DataRequired(), length(min=50)], render_kw={"type": "text",
                                                                                                       "class": "form-control",
                                                                                                       "placeholder": "Description",
                                                                                                       "style": "background-color:#ce5a67; border: 0px;",
                                                                                                       "rows": "10",
                                                                                                       "cols": "45"})
    short_description = TextAreaField("Short Description", validators=[DataRequired(), length(max=200)],
                                      render_kw={"type": "text",
                                                 "class": "form-control",
                                                 "placeholder": "Short Description",
                                                 "style": "background-color:#ce5a67; border: 0px;",
                                                 "rows": "5", "cols": "45"})

    # img upload
    main_img = FileField("main_image", render_kw={"style": "background-color:#ce5a67; border-radius: 5px;",
                                                  "class": "w-100"})
    left_img1 = FileField("first_left_img", render_kw={"style": "background-color:#ce5a67; border-radius: 5px;",
                                                       "class": "w-100"})
    left_img2 = FileField("second_left_img", render_kw={"style": "background-color:#ce5a67; border-radius: 5px;",
                                                        "class": "w-100"})
    right_img1 = FileField("first_right_img", render_kw={"style": "background-color:#ce5a67; border-radius: 5px;",
                                                         "class": "w-100"})
    right_img2 = FileField("second_right_img", render_kw={"style": "background-color:#ce5a67; border-radius: 5px;",
                                                          "class": "w-100"})

    # img link
    main_img_l = StringField("Main Image Link", render_kw={"type": "text",
                                                           "class": "form-control",
                                                           "style": "background-color:#ce5a67; border: 0px;",
                                                           "placeholder": "Main Image Link"})
    left_img1_l = StringField("First Image Link", render_kw={"type": "text",
                                                             "class": "form-control",
                                                             "style": "background-color:#ce5a67; border: 0px;",
                                                             "placeholder": "First Image Link"})
    left_img2_l = StringField("Second Image Link", render_kw={"type": "text",
                                                              "class": "form-control",
                                                              "style": "background-color:#ce5a67; border: 0px;",
                                                              "placeholder": "Second Image Link"})
    right_img1_l = StringField("Third Image Link", render_kw={"type": "text",
                                                              "class": "form-control",
                                                              "style": "background-color:#ce5a67; border: 0px;",
                                                              "placeholder": "Third Image Link"})
    right_img2_l = StringField("Fourth Image Link", render_kw={"type": "text",
                                                               "class": "form-control",
                                                               "style": "background-color:#ce5a67; border: 0px;",
                                                               "placeholder": "Fourth Image Link"})

    goal = IntegerField("Short Description", validators=[DataRequired()], render_kw={"class": "form-control",
                                                                                     "placeholder": "Number of Signers",
                                                                                     "style": "background-color:#ce5a67; border: 0px;"})

    submit = SubmitField("პეტიციის შექმნა", render_kw={
        "class": "btn",
        "type": "submit",
        "style": "background-color: #ce5a67; margin: 20px; padding: 20px; margin-bottom: 40px;"
    })


class SignPetition(FlaskForm):
    name = StringField("Name", validators=[DataRequired()], render_kw={"class": "form-control",
                                                                       "placeholder": "Name",
                                                                       "style": "background-color:#ce5a67; border: 0px;"})
    surname = StringField("Surname", validators=[DataRequired()], render_kw={"class": "form-control",
                                                                             "placeholder": "Surname",
                                                                             "style": "background-color:#ce5a67; border: 0px;"})
    email = EmailField("Email", validators=[DataRequired(), Email()], render_kw={"class": "form-control",
                                                                                 "placeholder": "Email",
                                                                                 "style": "background-color:#ce5a67; border: 0px;"})
    personal_id = IntegerField("Personal ID", validators=[DataRequired()], render_kw={"class": "form-control",
                                                                                      "placeholder": "Personal ID",
                                                                                      "style": "background-color:#ce5a67; border: 0px;"})
    sex = SelectField("sex", validators=[DataRequired()],
                      choices=[("other", "აირჩიეთ სქესი"), ("male", "მამრობითი"), ("female", "მდედრობითი"),
                               ("other", "სხვა")],
                      render_kw={"class": "form-control",
                                 "placeholder": "Surname",
                                 "style": "background-color:#ce5a67; border: 0px;"})
    number = IntegerField("Phone Number", validators=[DataRequired()], render_kw={"class": "form-control",
                                                                                  "placeholder": "Phone Number",
                                                                                  "style": "background-color:#ce5a67; border: 0px;"})
    city = SelectField("City", validators=[DataRequired()],
                       choices=[("tbilisi", "თბილისი"), ("batumi", "ბათუმი"), ("kutaisi", "ქუთაისი"),
                                ("rustavi", "რუსთავი"), ("gori", "გორი"), ("poti", "ფოთი")],
                       render_kw={"class": "form-control",
                                  "placeholder": "City",
                                  "style": "background-color:#ce5a67; border: 0px;"})
    date = DateField("Birth Date", validators=[DataRequired()], render_kw={"class": "form-control",
                                                                           "placeholder": "Birth Date",
                                                                           "style": "background-color:#ce5a67; border: 0px;"})
    submit = SubmitField("ხელის მოწერა", render_kw={
        "class": "btn",
        "type": "submit",
        "style": "background-color: #ce5a67; margin: 20px; padding: 18px; margin-bottom: 40px;"
    })

src/views/petitions/routes.py
from flask import render_template, redirect, url_for, request, Blueprint, flash
from flask_login import current_user, login_required

from uuid import uuid4
from datetime import datetime
import os

from src.models import Petition, Signer, PetitionSigner, User
from src.config import Config, to_english
from src.views.petitions.forms import AddPetition, SignPetition

TEMPLATES_FOLDER = os.path.join(Config.BASE_DIRECTORY, "templates", "petitions")
petitions = Blueprint("petitions", __name__, template_folder=TEMPLATES_FOLDER)


@petitions.route("/petition/<string:name>")
def petition(name):
    to_display = Petition.query.filter(Petition.url_name == name).scalar()

    return render_template("petition.html", petition=to_display)


@petitions.route("/sign_petition", methods=["GET", "POST"])
def sign_petition():
    form = SignPetition()

    if current_user.is_authenticated:
        form = SignPetition(
            obj=current_user
        )

    petition_id = request.args.get("petition_id")

    if form.validate_on_submit():

        exists = False

        to_sign = Petition.query.get(petition_id)

        for signer in to_sign.signers:
            if signer.personal_id == form.personal_id.data or signer.email == form.email.data:
                exists = True

        if not exists:
            new_signer = Signer(
                name=form.name.data,
                surname=form.surname.data,
                email=form.email.data,
                personal_id=form.personal_id.data,
                sex=form.sex.data,
                number=form.number.data,
                city=form.city.data,
                date=form.date.data
            )

            new_signer.create()

            petition_signer = PetitionSigner(petition_id=petition_id, signer_id=new_signer.id)
            petition_signer.create()

            to_sign.votes = len(to_sign.signers)
            to_sign.save()

            return redirect(url_for("main.home"))
        else:
            flash("You have already signed this petition!")

    return render_template("sign-form.html", form=form)


@petitions.route("/create_petition", methods=["GET", "POST"])
@login_required
def create_petition():
    form = AddPetition()
    method = request.args.get("img")

    if form.validate_on_submit():

        name = to_english(form.name.data)
        upload_time = str(datetime.now().time())
        img_path = f"{name}{upload_time}"

        new_petition = Petition(
            user_id=current_user.id,
            name=form.name.data,
            title=form.title.data,
            address=form.address.data,
            description=form.description.data,
            short_description=form.short_description.data,
            url_name=name,
            img1=form.main_img_l.data,
            img2=form.left_img2_l.data,
            img3=form.left_img1_l.data,
            img4=form.right_img1_l.data,
            img5=form.right_img2_l.data,
            method="link",
            goal=form.goal.data,
            votes=0
        )

        if method == "upload":
            new_petition.method = "upload"
            os.makedirs(os.path.join(Config.UPLOAD_PATH, img_path), exist_ok=True)

            counter = 1
            for key, value in form.data.items():
                if key in Config.UPLOADING_IMAGES:
                    file = value

                    filename, filetype = file.filename.split(".")
                    filename = str(uuid4())
                    fullname = f"{filename}.{filetype}"

                    upload_path = os.path.join(Config.UPLOAD_PATH, img_path, fullname)
                    file.save(upload_path)

                    setattr(new_petition, f"img{counter}", f"./static/assets/{img_path}/{fullname}")
                    counter += 1

        new_petition.create()

        return redirect(url_for("main.home"))

    return render_template("create-petition.html", form=form, img=method)

src/templates/petitions/create-petition.html
{% extends "layouts/base.html" %}

{% block content %}
<div class="container text-center text_div">
    <h2 style="margin:20px; text-align: center;">შექმენი შენი პეტიცია</h2>
    <hr>
    <div class="d-flex justify-content-center">
        <form method="post" enctype="multipart/form-data">
            {{ form.hidden_tag() }}

            <br>
            <hr>

            <div class="input-group mb-3">
                <button class="btn dropdown-toggle w-100" type="button" data-bs-toggle="dropdown"
                    aria-expanded="false" style="background-color:#ce5a67;">აირჩიეთ სურათის ატვირთვის მეთოდი </button>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{{ url_for('petitions.create_petition', img='upload') }}">სურათის ატვირთვა</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('petitions.create_petition', img='link') }}">სურათის ლინკი</a></li>
                </ul>

            </div>
            <hr>
            <br>

            {% if img == "upload" %}
                <div class="input-group mb-3">
                    <label class="form-label w-100">მთავარი სურათი</label>
                    {{ form.main_img }}
                </div>
                <div class="input-group mb-3">
                    <label class="form-label w-100">პირველი სურათი</label>
                    {{ form.left_img1 }}
                </div>
                <div class="input-group mb-3">
                    <label class="form-label w-100">მეორე სურათი</label>
                    {{ form.left_img2 }}
                </div>
                <div class="input-group mb-3">
                    <label class="form-label w-100">მესამე სურათი</label>
                    {{ form.right_img1 }}
                </div>
                <div class="input-group mb-3">
                    <label class="form-label w-100">მეოთხე სურათი</label>
                    {{ form.right_img2 }}
                </div>

            {% else %}

                <div class="mb-3">
                    <label class="form-label">მთავარი სურათი</label>
                    {{ form.main_img_l }}
                </div>
                <div class="mb-3">
                    <label class="form-label">პირველი სურათი</label>
                    {{ form.left_img1_l }}
                </div>
                <div class="mb-3">
                    <label class="form-label">მეორე სურათი</label>
                    {{ form.left_img2_l }}
                </div>
                <div class="mb-3">
                    <label class="form-label">მესამე სურათი</label>
                    {{ form.right_img1_l }}
                </div>
                <div class="mb-3">
                    <label class="form-label">მეოთხე სურათი</label>
                    {{ form.right_img2_l }}
                </div>
            {% endif %}
            
            <br>
            <br>
            <hr> 
            <label class="form-label w-100">შეიყვანეთ ინფორმაცია</label>
            <hr>
            <br>

            <div class="mb-3">
                <label class="form-label">დასახელება</label>
                {{ form.name }}
            </div>

            <div class="mb-3">
                <label class="form-label">სათაური</label>
                {{ form.title }}
            </div>

            <div class="mb-3">
                <label class="form-label">ადრესატი</label>
                {{ form.address }}
            </div>

            <div class="mb-3">
                <label class="form-label">ტექსტი</label>
                {{ form.description }}
            </div>

            <div class="mb-3">
                <label class="form-label">მოკლე მიმოხილვა</label>
                {{ form.short_description }}
            </div>

            <div class="mb-3">
                <label class="form-label">საჭირო ხელმოწერების რაოდენობა</label>
                {{ form.goal }}
            </div>
            <br>
            {{ form.submit }}
        </form>
    </div>
</div>
{% endblock %}

src/templates/petitions/petition.html
{% extends "layouts/base.html" %}
{% from "macros.html" import modify_link, calculate_percentage %}

{% block title %}
    <title>{{ petition["name"] }}</title>
{% endblock %}

{% block content %}
<div class="container mt-4 text-center">
    <h1>პეტიცია: {{ petition.title }}</h1>
    <hr>
</div>
<div class="container mt-4">
    <div class="row gy-4 text-center">
        <div class="col-xxl col-xl-12 col-lg-12 col-md-12 col-sm-12">
            <img src="{{ modify_link(petition.method).strip() }}{{ petition.img2 }}" width="200px" height="130px">
        </div>
        <div class="col-xxl col-xl-12 col-lg-12 col-md-12 col-sm-12">
            <img src="{{ modify_link(petition.method).strip() }}{{ petition.img3 }}" width="250px" height="180px">
        </div>
        <div class="col-xxl col-xl-12 col-lg-12 col-md-12 col-sm-12">
            <img src="{{ modify_link(petition['method']).strip() }}{{ petition.img1 }}" width="300px" height="275px">
        </div>
        <div class="col-xxl col-xl-12 col-lg-12 col-md-12 col-sm-12">
            <img src="{{ modify_link(petition['method']).strip() }}{{ petition.img4 }}" width="250px" height="180px">
        </div>
        <div class="col-xxl col-xl-12 col-lg-12 col-md-12 col-sm-12">
            <img src="{{ modify_link(petition['method']).strip() }}{{ petition.img5 }}" width="200px" height="130px">
        </div>
    </div>
    <div class="text_div">
        <h2>ᲐᲓᲠᲔᲡᲐᲢᲘ: <em>{{ petition.address }}</em></h2>
        <hr>
        <p class="text-center text-break" id="text">{{ petition.description }}</p>
        <br>
        <br>

        {% if petition.votes != petition.goal %}
            <div class="container text-center">
                <h3>ხელმომწერთა რაოდენობა</h3>
                <hr>
                {% if petition.votes == 0 %}
                    <div class="progress" role="progressbar" aria-label="Example with label" aria-valuemin="0" aria-valuemax="100" style="height: 35px; margin: 30px 50px;">
                        <div class="progress-bar overflow-visible text-dark" {{ calculate_percentage(petition.votes, petition.goal, False, True) }}>
                            {{ petition.votes }}/{{ petition.goal }}
                        </div>
                    </div>
                {% else %}
                    <div class="progress" role="progressbar" aria-label="Example with label" aria-valuemin="0" aria-valuemax="100" style="height: 35px; margin: 30px 50px;">
                        <div class="progress-bar overflow-visible text-dark" {{ calculate_percentage(petition.votes, petition.goal) }}>
                            {{ petition.votes }}/{{ petition.goal }}
                        </div>
                    </div>
                {% endif %}
                <br>
            </div>

            <div class="button_align">
                <a href="{{ url_for('petitions.sign_petition', petition_id = petition.id) }}"> <button class="butn" type="button">ხელის მოწერა</button> </a>
            </div>
        {% else %}
            <div class="container text-center">
                <h3>პეტიცია დასრულებულია</h3>
                <hr>
                <div class="progress" role="progressbar" aria-label="Example with label" aria-valuemin="0" aria-valuemax="100" style="height: 35px; margin: 30px 50px;">
                    <div class="progress-bar overflow-visible text-dark bg-success" {{ calculate_percentage(petition.votes, petition.goal, True) }}>
                        {{ petition.votes }}/{{ petition.goal }}
                    </div>
                </div>
                <br>
            </div>
        {% endif %}
    </div>
</div>
{% endblock %}

src/templates/petitions/sign-form.html
{% extends "layouts/base.html" %}

{% block content %}
<div class="container text-center text_div">
    <h2 style="margin:20px; text-align: center;">პეტიციაზე ხელის მოწერა</h2>
    <hr>
    <div class="d-flex justify-content-center">
        <form method="post" enctype="multipart/form-data">

            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-danger d-flex align-items-center" role="alert">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}

            {{ form.hidden_tag() }}

            <br>

            <div class="mb-3">
                <label class="form-label">სახელი</label>
                {{ form.name }}
            </div>

            <div class="mb-3">
                <label class="form-label">გვარი</label>
                {{ form.surname }}
            </div>

            <div class="mb-3">
                <label class="form-label">ელ-ფოსტა</label>
                {{ form.email }}
            </div>

            <div class="mb-3">
                <label class="form-label">პირადი ნომერი</label>
                {{ form.personal_id }}
            </div>

            <div class="mb-3">
                <label class="form-label">სქესი</label>
                {{ form.sex }}
            </div>

            <div class="mb-3">
                <label class="form-label">ტელეფონის ნომერი</label>
                {{ form.number }}
            </div>

            <div class="mb-3">
                <label class="form-label">საცხოვრებელი ქალაქი</label>
                {{ form.city }}
            </div>

            <div class="mb-3">
                <label class="form-label">დაბადების თარიღი</label>
                {{ form.date }}
            </div>

            <br>
            {{ form.submit }}
        </form>
    </div>
</div>
{% endblock %}